@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US 2007
autonumber

actor "Professor" as Actor
participant ":Sistema" as System

activate Actor

Actor -> System : Pede para adicionar/atualizar questões de exame a um repositório
activate System

System --> Actor : Mostra a lista de disciplinas disponíveis (no estado in_progress) e que são lecionadas pelo próprio professor
Actor --> System : Pede para escolher uma disciplina
deactivate System

Actor -> System : Escolhe uma disciplina
activate System

System --> Actor : Pede para introduzir o caminho até ao ficheiro com a informação das questões a adicionar/atualizar
deactivate System

Actor -> System : Introduz o caminho até ao ficheiro
activate System

System --> Actor : Mostra os dados das questões e pede confirmação para as adicionar/atualizar
deactivate System

Actor -> System : Confirma a operação
activate System

System --> Actor : Informa o sucesso da operação
deactivate System

deactivate Actor

@enduml