@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram 1 (SSD) - US 1005
autonumber

actor "Gerente" as Gerente
participant ":Sistema" as Sistema

activate Gerente
    Gerente -> Sistema : Pede para definir professor responsável para uma disciplina
    activate Sistema
        Sistema --> Gerente : Mostra lista de disciplinas que ainda não tem professor responsável e pede para escolher uma
    deactivate Sistema

    Gerente -> Sistema : Escolhe a disciplina
    activate Sistema
        Sistema --> Gerente : Mostra a lista de professores e pede para escolher um
    deactivate Sistema

    Gerente -> Sistema : Escolhe um professor
    activate Sistema
        Sistema --> Gerente : Mostra a informação a ser tratada e pede confirmação
    deactivate Sistema

    Gerente -> Sistema : Confirma a operação
    activate Sistema
        Sistema --> Gerente : Informa o sucesso da operação
    deactivate Sistema

deactivate Gerente

@enduml