@startuml
title Sequence Diagram (SD) da us_1006_3

autonumber

actor "Professor" as USER
participant "<<presentation>> \n ListCourseUI" as UI
control "<<application>> \n ListCourseController" as CTRL
participant "<<application>> \n ListCourseService" as SERV
database "<<repository>> \n CourseRepository" as REPO
participant "<<domain>> \n course: Course" as CRS

activate USER

    USER -> UI : pedido para listar todos os cursos disponiveis para mim
    activate UI

    UI -> CTRL : create

    CTRL -> SERV : create

    UI -> CTRL : listTeacherCourses()
    activate CTRL

    CTRL -> SERV : allTeacherCourses(teacher)
    activate SERV

    SERV -> REPO : list = findAllTeacherCourses(teacher)
    activate REPO

    REPO --> SERV : list
    deactivate REPO

    SERV --> CTRL : list
    deactivate SERV

    CTRL --> UI : list
    deactivate CTRL

    UI --> USER : lista os cursos que o professor ensina
    deactivate UI

deactivate USER

@enduml