@startuml
title System Sequence Diagram (SSD) da us_1006_1

autonumber

actor "Gerente" as USER
participant ":System" as SYS

activate USER

    USER -> SYS : pedido para listar todos os cursos disponiveis para mim
    activate SYS

    SYS --> USER : lista todos os cursos
    deactivate SYS

deactivate USER

@enduml