@startuml

top to bottom direction

skinparam titleFontSize 25
title <u>Classes de Domínio para a US 1012</u>

'Course
package "<<aggregate>> Course" {
    entity Course <<entity>> <<root>>
    class CourseTitle <<(V, #FF8B40) value object>>
    class CourseCode <<(V, #FF8B40) value object>>
    class CourseDescription <<(V, #FF8B40) value object>>
    class CourseStatus <<(V, #FF8B40) value object>>
    class CourseEnrolmentLimits <<(V, #FF8B40) value object>> {
        minimumEnrolments
        maximumEnrolments
    }
    class CourseDate <<(V, #FF8B40) value object>> {
        startDate
        endDate
    }
}


'Class
package "<<aggregate>> Class" {
    entity Class <<entity>> <<root>>
    class ClassTitle <<(V, #FF8B40) value object>>
    class ClassDuration <<(V, #FF8B40) value object>>
    class ClassDayOfTheWeek <<(V, #FF8B40) value object>>
    class ClassStartTime <<(V, #FF8B40) value object>>
    entity ClassInstance <<entity>>
    class ClassInstanceDateTime <<(V, #FF8B40) value object>>{
        newDateTime
        previousDateTime
    }
}

'Teacher
package "<<aggregate>> Teacher" {
    entity Teacher <<entity>> <<root>>
    class Acronym <<(V, #FF8B40) value object>>
}


Teacher -down-> Acronym


Course -down-> CourseTitle
Course -down-> CourseCode
Course -down-> CourseDescription
Course -down-> CourseStatus
Course -down-> CourseEnrolmentLimits
Course -down-> CourseDate
Course "1" --> "1..*" Class : has >
Course "1" --> "1" Teacher : has responsible >
Course "1..*" --> "1..*" Teacher : is taught >


Class -down-> ClassTitle
Class -down-> ClassDuration
Class -down-> ClassDayOfTheWeek
Class -down-> ClassStartTime
Class "1..*" --> "1" Teacher : schedule by >
Class "1" --> "0..*" ClassInstance : reschedule >

ClassInstance -down-> ClassInstanceDateTime

@enduml