@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US 3010
autonumber

actor "Utilizador" as Actor
participant ":Sistema" as System

activate Actor

Actor -> System : Pede para arquivar uma board
activate System

System --> Actor : Mostra a lista de board ativas em que o utilizador é dono
System --> Actor : Pede para escolher a board a arquivar
deactivate System

Actor -> System : Escolhe a board a arquivar
activate System

System --> Actor : Mostra os dados da board a arquivar
System --> Actor : Pede confirmação da operação
deactivate System

Actor -> System : Confirma a operação
activate System

System --> Actor : Informa o sucesso da operação
deactivate System

deactivate Actor

@enduml